apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: basket-web
  name: basket-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: basket-web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.network/frontend: "true"
        io.kompose.service: basket-web
    spec:
      containers:
      - args:
        - bash
        - -c
        - python3 ./manage.py makemigrations && python3 ./manage.py migrate
          && gunicorn api.wsgi:application --bind 0.0.0.0:8004
        env:
        - name: DJANGO_SUPERUSER_PASSWORD
          value: admin
        image: ersmsmusicstore.azurecr.io/basket-web:latest
        imagePullPolicy: Always
        name: basket-web
        ports:
        - containerPort: 8004
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
