apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  selector:
    matchLabels:
      io.kompose.service: nginx
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - image: services-nginx
        imagePullPolicy: Never
        name: nginx
        ports:
        - containerPort: 80