apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: user-web
  name: user-web
spec:
  ports:
  - name: "8003"
    port: 8003
    targetPort: 8003
  selector:
    io.kompose.service: user-web
status:
  loadBalancer: {}
