apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: user-web
  name: user-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: user-web
    spec:
      containers:
      - args:
        - bash
        - -c
        - python3 ./manage.py makemigrations && python3 ./manage.py migrate && python
          manage.py createsuperuser --noinput --email admin@admin.com && gunicorn
          api.wsgi:application --bind 0.0.0.0:8003
        env:
        - name: DJANGO_SUPERUSER_PASSWORD
          value: admin
        image: user-web
        imagePullPolicy: Never
        name: user-web
        ports:
        - containerPort: 8003
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
