apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: vue-frontend
  name: vue-frontend
spec:
  type: LoadBalancer
  ports:
  - name: "8800"
    port: 8800
    targetPort: 80
  selector:
    io.kompose.service: vue-frontend
status:
  loadBalancer: {}
