# Generated by Django 2.2.13 on 2021-06-01 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasketSession',
            fields=[
                ('basket_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], max_length=6)),
            ],
            options={
                'verbose_name': 'BasketSession',
                'verbose_name_plural': 'BasketSession',
                'ordering': ('basket_id',),
            },
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('basket_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('catalog_item_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('basket_session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BasketSession')),
            ],
            options={
                'verbose_name': 'BasketItem',
                'verbose_name_plural': 'BasketItem',
                'ordering': ('catalog_item_id',),
            },
        ),
    ]
