# Generated by Django 2.2.13 on 2021-06-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='slug',
            field=models.CharField(default='testprod', max_length=255),
        ),
    ]
