openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /orders/:
    get:
      operationId: listOrders
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
          description: ''
      tags:
      - orders
    post:
      operationId: createOrder
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Order'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: ''
      tags:
      - orders
  /orders/{order_id}/:
    get:
      operationId: retrieveOrder
      description: ''
      parameters:
      - name: order_id
        in: path
        required: true
        description: A unique integer value identifying this order.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: ''
      tags:
      - orders
    put:
      operationId: updateOrder
      description: ''
      parameters:
      - name: order_id
        in: path
        required: true
        description: A unique integer value identifying this order.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Order'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: ''
      tags:
      - orders
    patch:
      operationId: partialUpdateOrder
      description: ''
      parameters:
      - name: order_id
        in: path
        required: true
        description: A unique integer value identifying this order.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Order'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: ''
      tags:
      - orders
    delete:
      operationId: destroyOrder
      description: ''
      parameters:
      - name: order_id
        in: path
        required: true
        description: A unique integer value identifying this order.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - orders
  /orderitems/:
    get:
      operationId: listOrderItems
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderItem'
          description: ''
      tags:
      - orderitems
    post:
      operationId: createOrderItem
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderItem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OrderItem'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OrderItem'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderItem'
          description: ''
      tags:
      - orderitems
  /orderitems/{order_item_id}/:
    get:
      operationId: retrieveOrderItem
      description: ''
      parameters:
      - name: order_item_id
        in: path
        required: true
        description: A unique integer value identifying this order item.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderItem'
          description: ''
      tags:
      - orderitems
    put:
      operationId: updateOrderItem
      description: ''
      parameters:
      - name: order_item_id
        in: path
        required: true
        description: A unique integer value identifying this order item.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderItem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OrderItem'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OrderItem'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderItem'
          description: ''
      tags:
      - orderitems
    patch:
      operationId: partialUpdateOrderItem
      description: ''
      parameters:
      - name: order_item_id
        in: path
        required: true
        description: A unique integer value identifying this order item.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderItem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OrderItem'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OrderItem'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderItem'
          description: ''
      tags:
      - orderitems
    delete:
      operationId: destroyOrderItem
      description: ''
      parameters:
      - name: order_item_id
        in: path
        required: true
        description: A unique integer value identifying this order item.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - orderitems
  /payments/:
    get:
      operationId: listPayments
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Payment'
          description: ''
      tags:
      - payments
    post:
      operationId: createPayment
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payment'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Payment'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Payment'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
          description: ''
      tags:
      - payments
  /payments/{payment_id}/:
    get:
      operationId: retrievePayment
      description: ''
      parameters:
      - name: payment_id
        in: path
        required: true
        description: A unique integer value identifying this payment.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
          description: ''
      tags:
      - payments
    put:
      operationId: updatePayment
      description: ''
      parameters:
      - name: payment_id
        in: path
        required: true
        description: A unique integer value identifying this payment.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payment'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Payment'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Payment'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
          description: ''
      tags:
      - payments
    patch:
      operationId: partialUpdatePayment
      description: ''
      parameters:
      - name: payment_id
        in: path
        required: true
        description: A unique integer value identifying this payment.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payment'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Payment'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Payment'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
          description: ''
      tags:
      - payments
    delete:
      operationId: destroyPayment
      description: ''
      parameters:
      - name: payment_id
        in: path
        required: true
        description: A unique integer value identifying this payment.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - payments
components:
  schemas:
    Order:
      type: object
      properties:
        order_id:
          type: integer
          readOnly: true
        status:
          enum:
          - '0'
          - '1'
          - '2'
          - '3'
          - '4'
          type: string
        total_amount:
          type: string
          format: decimal
          multipleOf: 0.01
          maximum: 1000000
          minimum: -1000000
        order_items:
          type: array
          items:
            type: string
          readOnly: true
        payments:
          type: array
          items:
            type: string
          readOnly: true
      required:
      - total_amount
    OrderItem:
      type: object
      properties:
        order_item_id:
          type: integer
          readOnly: true
        catalog_item_id:
          type: integer
          maximum: 2147483647
          minimum: 0
        quantity:
          type: integer
          maximum: 2147483647
          minimum: 0
        price:
          type: string
          format: decimal
          multipleOf: 0.01
          maximum: 100000
          minimum: -100000
        order_id:
          type: integer
      required:
      - catalog_item_id
      - quantity
      - price
      - order_id
    Payment:
      type: object
      properties:
        payment_id:
          type: integer
          readOnly: true
        status:
          enum:
          - '0'
          - '1'
          - '2'
          - '3'
          type: string
        user_id:
          type: integer
          maximum: 2147483647
          nullable: true
          minimum: 0
        order_id:
          type: integer
      required:
      - order_id
