version: '3.7'

services:
  catalog-web:
    image: catalog-web:latest
    build: ./catalog
    command: bash -c "python3 ./manage.py makemigrations &&
                      python3 ./manage.py migrate &&
                      gunicorn api.wsgi:application --bind 0.0.0.0:8002"
    expose:
      - 8002
    restart: always
    links:
      - postgres-db

  user-web:
    image: user-web:latest
    build: ./user
    command: bash -c "python3 ./manage.py makemigrations &&
                      python3 ./manage.py migrate &&
                      python manage.py createsuperuser --noinput --email admin@admin.com &&
                      gunicorn api.wsgi:application --bind 0.0.0.0:8003"
    expose:
      - 8003
    restart: always
    environment:
      DJANGO_SUPERUSER_PASSWORD: admin
    links:
      - postgres-db

  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  nginx:
    image: services-nginx:latest
    build: ./web
    ports:
      - 9090:80
    links:
      - frontend

  frontend:
    image: frontend:latest
    build: ./frontend
    command: http-server dist -a 0.0.0.0 --port 8800
    expose:
      - 8800
    links:
      - catalog-web
      - user-web
