# Generated by Django 3.2.3 on 2021-05-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('catalog_item', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'oczekujace'), ('2', 'przyjete'), ('3', 'zrealizowane'), ('4', 'odrzucone'), ('5', 'inne')], default='1', max_length=20)),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
