# Generated by Django 3.2.3 on 2021-06-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_payment_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user_id',
        ),
        migrations.AddField(
            model_name='order',
            name='catalog_item',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
