# Generated by Django 3.2.3 on 2021-06-08 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210608_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='catalog_item',
        ),
    ]
