# Generated by Django 2.2.13 on 2021-06-02 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('opinion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=200)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('catalog_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CatalogItem')),
            ],
        ),
    ]
