# Generated by Django 2.2.13 on 2021-06-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210602_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='opinion_id',
            new_name='image_id',
        ),
    ]
