# Generated by Django 2.2.13 on 2021-06-10 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210603_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='catalog_item_id',
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ProductImage'),
        ),
    ]
