# Generated by Django 2.2.13 on 2021-06-10 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210610_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='catalog_item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.CatalogItem'),
        ),
    ]
